// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQByALIHhzv2W_ylSUe5EO5jx0BfhCXXY',
    appId: '1:957040950533:web:cd5ddb942466283acf4b6c',
    messagingSenderId: '957040950533',
    projectId: 'kopi-7148a',
    authDomain: 'kopi-7148a.firebaseapp.com',
    storageBucket: 'kopi-7148a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQlnvTxHMsld4_Ea9w0eEEvFT37iG9rss',
    appId: '1:957040950533:android:45810e8c6d44dd80cf4b6c',
    messagingSenderId: '957040950533',
    projectId: 'kopi-7148a',
    storageBucket: 'kopi-7148a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTAn-dPnvE7RSmZe7UR2JlfEAB4PSAU0',
    appId: '1:957040950533:ios:ba319ea7db8ca546cf4b6c',
    messagingSenderId: '957040950533',
    projectId: 'kopi-7148a',
    storageBucket: 'kopi-7148a.firebasestorage.app',
    iosBundleId: 'com.example.kopi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoTAn-dPnvE7RSmZe7UR2JlfEAB4PSAU0',
    appId: '1:957040950533:ios:ba319ea7db8ca546cf4b6c',
    messagingSenderId: '957040950533',
    projectId: 'kopi-7148a',
    storageBucket: 'kopi-7148a.firebasestorage.app',
    iosBundleId: 'com.example.kopi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQByALIHhzv2W_ylSUe5EO5jx0BfhCXXY',
    appId: '1:957040950533:web:9ebb479ba38312a5cf4b6c',
    messagingSenderId: '957040950533',
    projectId: 'kopi-7148a',
    authDomain: 'kopi-7148a.firebaseapp.com',
    storageBucket: 'kopi-7148a.firebasestorage.app',
  );

}